[package]
name = "win32-getlocaleinfo"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.62.2", features = [] }

[features]
default = ["global-pref"]

legacy-methods = [
    "windows/Win32_Globalization",
    "windows/Win32_System_SystemServices",
]
global-pref = ["windows/System_UserProfile"]

nightly = []
