name: Build Releases
on:
  push:
    branches: [master]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
permissions:
  contents: write
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      rev_count: ${{ steps.vars.outputs.rev_count }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Get revision count
        id: vars
        shell: bash
        run: |
          rev_count=$(git rev-list --count HEAD)
          echo "rev_count=${rev_count}" >> $GITHUB_OUTPUT
      - name: Create Draft Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: r${{ steps.vars.outputs.rev_count }}
          prerelease: false
          make_latest: true
          draft: true
  build-and-upload:
    name: Build and Upload for ${{ matrix.target }}
    needs: create-release
    runs-on: ${{ matrix.os }}
    env:
      RUST_BIN_NAME: "win32-locale-info"
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            suffix: .exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            suffix: .exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.target }}
          shared-key: "main"
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
      - name: Prepare assets
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ env.RUST_BIN_NAME }}${{ matrix.suffix }} .
          tar -cvzf ${{ matrix.target }}.tar.gz LICENSE ${{ env.RUST_BIN_NAME }}${{ matrix.suffix }}
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.target }}.tar.gz
          tag_name: r${{ needs.create-release.outputs.rev_count }}
  publish-release:
    name: Publish Release
    needs:
      - create-release
      - build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: r${{ needs.create-release.outputs.rev_count }}
          draft: false
